[phases.setup]
nixPkgs = ["python3", "cairo", "pango", "gdk-pixbuf", "libffi", "zlib", "jpeg", "openjpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
